### ISSUE TITLE
Attention aux injections SQL

### ISSUE THREAD

**Issue by fliewight** [WildCodeSchool/2023-03-remote-fr-php-huitres-tafforet#84]

**Comment by fliewight** [comment]
Les données que j'ai entré ne sont pas vérifiées via PHP (champs manquants requis), je suppose que les injections ne sont pas traitées ? Regarde mon entrée via la BDD pour t'en assurer

**Comment by ninaschadel** [comment]
On est protégés contre les injections grace aux bindValue. 
Par contre, on rajoutera des if(empty) pour ne pas recevoir de champ vide. Mais aucun soucis niveau sécurité selon nous

**Comment by fliewight** [comment]
Ok nikel alors ;) good project
